"""empty message

Revision ID: 1c53fdef4589
Revises: cafcfd3d58aa
Create Date: 2020-09-29 18:17:15.953085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c53fdef4589'
down_revision = 'cafcfd3d58aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
