"""empty message

Revision ID: fc2488836a5d
Revises: 1c53fdef4589
Create Date: 2020-09-29 18:33:20.965665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2488836a5d'
down_revision = '1c53fdef4589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_completion_user_id_fkey', 'course_completion', type_='foreignkey')
    op.create_foreign_key(None, 'course_completion', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('course_like_user_id_fkey', 'course_like', type_='foreignkey')
    op.create_foreign_key(None, 'course_like', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('enrolment_user_id_fkey', 'enrolment', type_='foreignkey')
    op.create_foreign_key(None, 'enrolment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('user_user_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('user', 'id')
    op.drop_constraint(None, 'enrolment', type_='foreignkey')
    op.create_foreign_key('enrolment_user_id_fkey', 'enrolment', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'course_like', type_='foreignkey')
    op.create_foreign_key('course_like_user_id_fkey', 'course_like', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'course_completion', type_='foreignkey')
    op.create_foreign_key('course_completion_user_id_fkey', 'course_completion', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
